#!/usr/bin/env bash
# Key is from https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/app/DefaultSecureStorage.java#L32
# Converted to hexadecimal like so in Python:
# >>> import struct
# >>> struct.pack('<16b', 0, 1, 2, etc).hex()
KEY=babb4a9f774ab853c96c2d653dfe544a
prefix="${HOME}/.local/share"
if sw_vers >/dev/null 2>&1; then
    prefix="${HOME}/Library"
fi
CONFIG_JSON="${prefix}/DBeaverData/workspace6/General/.dbeaver/credentials-config.json"
openssl aes-128-cbc -d -K "$KEY" -iv 00000000000000000000000000000000 \
    -in "$CONFIG_JSON" | dd bs=1 skip=16 2>/dev/null
echo
