#!/usr/bin/env bash
# Decrypt and display your DBeaver credentials. The output is a JSON string.
KEY=babb4a9f774ab853c96c2d653dfe544a
prefix="$HOME/.local/share"
if sw_vers > /dev/null 2>&1; then
    prefix="$HOME/Library"
elif [ -n "$APPDATA" ]; then
    prefix="${APPDATA}"
fi
CONFIG_JSON="$prefix/DBeaverData/workspace6/General/.dbeaver/credentials-config.json"
openssl aes-128-cbc -d -K "$KEY" -iv 00000000000000000000000000000000 -in "$CONFIG_JSON" |
    dd bs=1 skip=16 2> /dev/null
echo
