.TH dbeaver-creds 1 "September 2023" "dbeaver 0.0.1" "User Commands"
.SH Name
.P
dbeaver-creds \- display your DBeaver credentials.
.SH SYNOPSIS
.B dbeaver-creds
.SH DESCRIPTION
.P
Decrypt and display your DBeaver credentials. The output is a JSON string.
.P
If the credentials file cannot be found, the exit status will be > 0.
