concurrency:
  cancel-in-progress: false
  group: 'pages'
jobs:
  pages:
    environment:
      name: 'github-pages'
      url: '${{ steps.deployment.outputs.page_url }}'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v6.0.2'
        with:
          fetch-depth: 0
      - name: 'Setup Pages'
        uses: 'actions/configure-pages@v6'
      - name: 'Install dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
      - name: 'Configure'
        run: >-
          cmake -DCMAKE_BUILD_TYPE=Release -B ${{ github.workspace }}/build -DBUILD_DOCS=ON
      - name: 'Build documentation'
        run: 'cmake --build ${{ github.workspace }}/build --target docs --verbose'
      - name: 'Upload artifact'
        uses: 'actions/upload-pages-artifact@v5'
        with:
          path: '${{ github.workspace }}/build/html'
      - id: 'deployment'
        name: 'Deploy to GitHub Pages'
        uses: 'actions/deploy-pages@v5'
name: 'GitHub Pages'
'on':
  push:
    branches:
      - 'master'
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/CMakeLists.txt'
      - '.github/workflows/pages.yml'
      - 'Doxyfile.in'
permissions:
  contents: 'read'
  id-token: 'write'
  pages: 'write'
