---
jobs:
  build:
    name: PSScriptAnalyzer
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f
        with:
          includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
          output: results.sarif
          path: .\
          recurse: true
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
name: PSScriptAnalyzer
'on':
  pull_request:
    branches: ['master']
  push:
    branches: ['master']
  schedule:
    - cron: 37 13 * * 4
permissions:
  contents: read
